twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
        - '@Easy/form/fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
